Docs sara
brainglobe/website pull request #37
Opened 2023-06-24 14:46 UTC by SaraMederos

Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).

## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**

**What does this PR do?**

## References

Please reference any existing issues/PRs that relate to this PR.

## How has this PR been tested?

Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.

## Is this a breaking change?

If this PR breaks any existing functionality, please explain how and why.

## Does this PR require an update to the documentation?

If any features have changed, or have been added. Please explain how the documentation has been updated (and link to the associated PR). See [here](https://docs.cellfinder.info/for-developers/documentation) for details.

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [ ] The code has been formatted with [pre-commit](https://pre-commit.com/)

2023-06-24 14:47 UTC, SaraMederos commented
This is a draft PR for the docs on the segmenting external layers

2023-06-26 07:56 UTC, adamltyson requested changes
Looks good, thanks @SaraMederos. I've added a few comments. I also added this page to the table of contents so that it shows up on the main brainreg-segment page.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +To analyze the results from segmentation layers of your images within the context of the atlas-aligned image, allow you to import external layers that will be analyzed by brainreg-segment.
It would be great if this first section could explain the rationale behind this option a bit better. Something like "While manual analysis of regions works well for many applications, sometimes automated methods are needed. Napari has lots of plugins that can do X, Y, Z.".

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +{% endhint %}
Is this needed? It looks like it was copied from the old documentation, so it won't render in the new sphinx docs.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +{% hint style="info" %}
This syntax is also from the old docs and won't work in sphinx. Only the `:::{note}` syntax will work.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +  * If `to brainrender` is selected, then each region will generate the obj file that you can use later for rendering. See [Analyze and visualize tracing experiments](/tutorials/tracing-tracking) for
As far as possible, it would be great to not duplicate any sections of the documentation. Could you link to the other page that has this info? Then we only need to keep one section up to date.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +Additional installations to your enviroment are needed
```suggestion
Additional installations to your environment are needed
```

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +Additional installations to your enviroment are needed
It would be great to explain this a bit more.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +* You can utilize other segmentation plugins to generate an external layer according to your convenience. These plugins enable you to generate threshold or binary files in your desired image. For exa
Rather than replicating the instructions for installing a napari plugin here, could we link to e.g. the [napari hub](https://www.napari-hub.org/plugins/napari-simpleitk-image-processing) then we can rely on them keeping the installation instructions up to date.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +Once the thresholded image is generated, you can save it by going to the File menu in Napari and selecting "Save As" or by using the appropriate saving option provided by the plugin.
This section is slightly confusing. It might be easier to frame the instructions around a simpler version of the process:
- Open brainre-segment
- Load registration results
- Use other plugin to segment e.g. `downsampled` 
- Add existing layer
- Analyse

Then it could be mentioned that the normal brainreg-segment save button will work on these extra layers (once added to the plugin). Saving/loading these layers works fine, but it might be unnecessary additional complexity for the user.

2023-06-26 07:56 UTC, adamltyson commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +* To perform segmentation, you have the option of using the simpleitk plugin or other napari plugins that utilize deep learning-based segmentation algorithms. Here's how you can use the napari-simple
Could we emphasise that `napari-simple-itk-image-processing` is _just one_ of many plugins that could be used?

2023-07-03 18:38 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +To analyze the results from segmentation layers of your images within the context of the atlas-aligned image, allow you to import external layers that will be analyzed by brainreg-segment.
Agree. Included now

2023-07-03 18:58 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +{% endhint %}
Solved

2023-07-03 18:59 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +{% hint style="info" %}
Solved

2023-07-03 19:35 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +  * If `to brainrender` is selected, then each region will generate the obj file that you can use later for rendering. See [Analyze and visualize tracing experiments](/tutorials/tracing-tracking) for
Done

2023-07-03 19:35 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +Additional installations to your enviroment are needed
included

2023-07-03 19:39 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +Additional installations to your enviroment are needed
included in note to see details explained in the text below

2023-07-03 19:39 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +* You can utilize other segmentation plugins to generate an external layer according to your convenience. These plugins enable you to generate threshold or binary files in your desired image. For exa
done

2023-07-03 20:03 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +Once the thresholded image is generated, you can save it by going to the File menu in Napari and selecting "Save As" or by using the appropriate saving option provided by the plugin.
done! :) I agree it is much easier to follow this way

2023-07-03 20:04 UTC, SaraMederos commented on docs/source/documentation/brainreg-segment/user-guide/segmenting-external-layers.md
> +* To perform segmentation, you have the option of using the simpleitk plugin or other napari plugins that utilize deep learning-based segmentation algorithms. Here's how you can use the napari-simple
done!

2023-07-03 20:33 UTC, SaraMederos commented
Uploading the new PR

2023-07-07 09:22 UTC, closed without merging